Make GOOS=js GOARCH=wasm a possible build target
ipfs/boxo pull request #573
Opened 2024-01-28 09:48 UTC by bahner

As writing files is not really applicable in WebAssembly create a noop filewriter to make compilation possible.

2024-01-28 11:26 UTC, bahner commented
Incidentally, I believe this closes issue #186

2024-02-04 20:18 UTC, bahner commented
@Jorropo when you take a look at this, then feel free to suggest actual writing to in-memory files. I just don't see any reason, but if there is then just holler.

2024-02-05 00:43 UTC, Jorropo commented
I would like to support WASM too but I want to you know that you havn't added anything to the test suite.
If we don't test WASM in CI I could merge it but with expectations that it's not maintained, experimental and could break at any moment.

2024-02-05 00:44 UTC, Jorropo requested changes
I don't think a new `filewriter_wasm` file is correct.
The STD emulates a unix filesystem on top of JS:
https://cs.opensource.google/go/go/+/master:src/os/file_unix.go;l=5?q=openFileNolog&ss=go%2Fgo

2024-02-05 01:14 UTC, Jorropo commented on files/filewriter_unix_test.go
> +// +build darwin linux netbsd openbsd freebsd dragonfly js,!wasm wasip1
Btw, it's been since 1.18 that `+build` isn't used anymore.
I think you should upgrade your version of go. :wink: :slightly_smiling_face:

2024-02-13 01:47 UTC, bahner commented
Hepp! Good feedback. A little busy here, but I'll follow up.

2026-05-05 12:26 UTC, lidel commented
Superseded by #935

2026-05-05 12:26 UTC, closed without merging